In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
%matplotlib inline

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

In [2]:
(2 * np.ones(20)) ** np.arange(1, 21) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
fmul = (0.1 * np.ones(6)) ** (3 * np.arange(0, 6))
smul = (0.2 * np.ones(6)) ** (4 * np.arange(0, 6))
np.sum(fmul * smul)

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
a = np.zeros((8, 8))

a[::2 , ::2] = 1
a[1::2 , 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
x = np.random.random((5, 2))
print(x)
x = np.array([np.sqrt(x[:, 0] ** 2 + x[:, 1] ** 2), np.arctan2(x[:, 1], x[:, 0])]).T; x

[[0.68536975 0.53612757]
 [0.54175249 0.06677743]
 [0.68083995 0.36188976]
 [0.47238662 0.47726076]
 [0.0366455  0.62046357]]


array([[0.87015198, 0.66382104],
       [0.54585253, 0.12264325],
       [0.77104296, 0.48855562],
       [0.67151095, 0.7905307 ],
       [0.6215448 , 1.51180338]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

In [6]:
x = np.random.random((10, 10))

idx = np.unravel_index(np.argmax(x), x.shape); idx

(4, 6)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
x = np.random.random((10, 2))
y = np.random.random((1, 2))

print(x)
print(y)

dist = np.sqrt((x[:, 0] - y[:, 0]) ** 2 + (x[:, 0] - y[:, 1]) ** 2)
x[np.argmin(dist), :]

[[0.92224134 0.03152049]
 [0.29529095 0.80699429]
 [0.13835508 0.50435642]
 [0.84448617 0.68278824]
 [0.31174971 0.33689199]
 [0.86757915 0.99837836]
 [0.22769805 0.83091516]
 [0.04775138 0.76635229]
 [0.86158669 0.75871943]
 [0.29526446 0.51566501]]
[[0.42466859 0.21225101]]


array([0.31174971, 0.33689199])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
x = 6 * np.random.random(10) - 3
first_mask = x < 0
second_mask = (0 <= x) & (x <= 2)
third_mask = x >= 2
x[first_mask] = x[first_mask] ** 2 + 2 * x[first_mask] + 6
x[second_mask] = x[second_mask] + 6
x[third_mask] = x[third_mask] ** 2 + 4 * x[third_mask] + 6
x

array([ 6.97320564,  5.49470211,  5.6013908 ,  8.42962075,  5.00696133,
        7.83302175,  7.75554404,  6.58226805,  6.9990672 , 21.00982955])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

In [9]:
a = np.random.random((10, 10))

a = a.T - np.mean(a, axis=1).T
a = a.T

np.mean(a, axis=1)

array([ 2.22044605e-17,  4.44089210e-17, -7.77156117e-17,  0.00000000e+00,
       -4.44089210e-17, -3.33066907e-17,  7.77156117e-17,  3.33066907e-17,
       -2.22044605e-17, -9.99200722e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
x = np.random.normal(loc=5, scale=2., size=1000)

mean = x.sum() / x.size
variance = ((x - mean) ** 2).sum() / x.size
mean, variance

(4.976735823557621, 3.73643733692602)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
a = np.ones((5, 5)) * np.arange(5)
a += a.T
a %= 5
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 0, 4]

In [13]:
def better_sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    partial = np.repeat(np.cumsum(x), c).reshape((len(x), c)).astype("float32")
    val = s * np.random.random(c)
    partial -= val.T
    partial[partial >= 0] = 0
    
    return np.argmax(partial, axis=0)

better_sample([50, 3, 1, 7, 20], 5)    

array([4, 0, 4, 1, 0])